workflows:
  version: 2
  main:
    jobs:
      - build-and-test

version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run: pylint *.py
      - run: wget https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
      - run: unzip packer_1.5.5_linux_amd64.zip && sudo mv packer /usr/local/bin
      - run: git clone https://github.com/cheuklau/trading-post-ops.git
      - run: cd trading-post-ops/v2/packer && packer build packer.json
