workflows:
  version: 2
  main:
    jobs:
      - build-and-test

version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run: sudo pip install -r requirements.txt
      - run: pylint *.py
